openapi: 3.0.0
info:
  title: Employee API
  description: RESTAPI for managing employee data
  version: 1.0.0
servers:
  - url: http://localhost:7000
paths:
  /docs:
    get:
      summary:  API documentation accessible
      responses:
        '200':
          description: Open API page

  /employees:

    get:
      summary: Get all employees
      responses:
        '200':
          description: A list of employees
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                    description: Total number of employees
                  average_years_with_company:
                    type: number
                    format: float
                    description: Average years with company
                  average_salary:
                    type: number
                    format: float
                    description: Average salary
                  employees:
                    type: array
                    items:
                      $ref: '#/components/schemas/Employee'

    post:
      summary: Add a new employee
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewEmployee'
      responses:
        '200':
          description: New employee added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConfirmationWithId'

  '/employees/{id}':

    get:
      summary: Get employee by ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the employee to get
          schema:
            type: integer
      responses:
        '200':
          description: Employee details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployeeById'

    put:
      summary: Update employee by ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the employee to update
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateEmployee'
      responses:
        '200':
          description: Employee with ID updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Confirmation'

    patch:
      summary: Modify employee by ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the employee to modify
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModifyEmployee'
      responses:
        '200':
          description: Employee with ID modified
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Confirmation'

    delete:
      summary: Delete employee by ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the employee to delete
          schema:
            type: integer
      responses:
        '200':
          description: Employee deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Confirmation'

components:
  schemas:

    Employee:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier for the employee
        name:
          type: string
          description: Name of the employee
        years_with_company:
          type: number
          format: float
          description: Years with the company
        department:
          type: string
          description: Department of the employee
        salary:
          type: number
          format: float
          description: Salary of the employee

    EmployeeById:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier for the employee
        name:
          type: string
          description: Name of the employee
        job_title:
          type: string
        department:
          type: string
          description: Department of the employee
        years_with_company:
          type: number
          format: float
          description: Years with the company
        salary:
          type: number
          format: float
          description: Salary of the employee

    NewEmployee:
      type: object
      required:
        - name
        - job_title
        - years_with_company
        - department
        - salary
      properties:
        name:
          type: string
        job_title:
          type: string
        years_with_company:
          type: number
          format: float
        department:
          type: string
        salary:
          type: number
          format: float

    UpdateEmployee:
      type: object
      required:
        - name
        - job_title
        - years_with_company
        - department
        - salary
      properties:
        name:
          type: string
        job_title:
          type: string
        years_with_company:
          type: number
          format: float
        department:
          type: string
        salary:
          type: number
          format: float

    ModifyEmployee:
      type: object
      properties:
        name:
          type: string
        job_title:
          type: string
        years_with_company:
          type: number
          format: float
        department:
          type: string
        salary:
          type: number
          format: float

    ConfirmationWithId:
      type: object
      properties:
        status:
          type: integer
          description: HTTP status code
        message:
          type: string
          description: Confirmation message
        id:
          type: integer
          description: ID of the new employee

    Confirmation:
      type: object
      properties:
        status:
          type: integer
          description: HTTP status code
        message:
          type: string
          description: Confirmation message